# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InstructionForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QWidget

class Ui_InstructionForm(QWidget):
    def __init__(self, parent):
        super(Ui_InstructionForm, self).__init__(parent)
        self.parent = parent
        self.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.Window)
        self.setupUi(self)
        self.show()

    def setupUi(self, InstructionForm):
        InstructionForm.setObjectName("InstructionForm")
        InstructionForm.setFixedSize(600, 280)
        self.Instruction_QPlainTextEdit = QtWidgets.QPlainTextEdit(InstructionForm)
        self.Instruction_QPlainTextEdit.setGeometry(QtCore.QRect(10, 10, 580, 250))
        self.Instruction_QPlainTextEdit.setObjectName("Instruction_QPlainTextEdit")
        self.Instruction_QPlainTextEdit.setReadOnly(True)
        self.retranslateUi(InstructionForm)
        QtCore.QMetaObject.connectSlotsByName(InstructionForm)

    def retranslateUi(self, InstructionForm):
        _translate = QtCore.QCoreApplication.translate
        InstructionForm.setWindowTitle(_translate("InstructionForm", "Инструкция"))
        self.Instruction_QPlainTextEdit.setPlainText(_translate("InstructionForm", "Для управления используются стрелочки.\n"
"\n"
"Нажатием стрелки игрок может скинуть все плитки игрового поля в одну из 4 сторон. Если при сбрасывании две плитки одного номинала «налетают» одна на другую, то они превращаются в одну, номинал которой равен сумме соединившихся плиток. После каждого хода на свободной секции поля появляется новая плитка номиналом «2» или «4». Если при нажатии кнопки местоположение плиток или их номинал не изменится, то ход не совершается\n"
"\n"
"Если в одной строчке или в одном столбце находится более двух плиток одного номинала, то при сбрасывании они начинают соединяться с той стороны, в которую были направлены. Например, находящиеся в одной строке плитки (4, 4, 4) после хода влево превратятся в (8, 4), а после хода вправо — в (4, 8). Данная обработка неоднозначности позволяет более точно формировать стратегию игры.\n"
"\n"
"За каждое соединение игровые очки увеличиваются на номинал получившейся плитки.\n"
"\n"
"Игра заканчивается поражением, если после очередного хода невозможно совершить действие.\n"
"\n"
"Приятной игры!"))