# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OptionsForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QWidget


class Ui_OptionsForm(QWidget):
    def __init__(self, parent):
        super(Ui_OptionsForm, self).__init__(parent)
        self.parent = parent
        self.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.Window)
        self.setupUi(self)
        self.show()
    def setupUi(self, OptionsForm):
        OptionsForm.setObjectName("OptionsForm")
        OptionsForm.resize(345, 205)
        self.ValueForWin_ComboBox = QtWidgets.QComboBox(OptionsForm)
        self.ValueForWin_ComboBox.setGeometry(QtCore.QRect(210, 50, 120, 25))
        self.ValueForWin_ComboBox.setObjectName("ValueForWin_ComboBox")
        self.MinValueForNewPlate_ComboBox = QtWidgets.QComboBox(OptionsForm)
        self.MinValueForNewPlate_ComboBox.setGeometry(QtCore.QRect(210, 90, 120, 25))
        self.MinValueForNewPlate_ComboBox.setObjectName("MinValueForNewPlate_ComboBox")
        self.SaveOptions_PushButton = QtWidgets.QPushButton(OptionsForm)
        self.SaveOptions_PushButton.setGeometry(QtCore.QRect(210, 160, 120, 25))
        self.SaveOptions_PushButton.setObjectName("SaveOptions_PushButton")
        self.TextForOptions_Label = QtWidgets.QLabel(OptionsForm)
        self.TextForOptions_Label.setGeometry(QtCore.QRect(10, 10, 320, 16))
        self.TextForOptions_Label.setObjectName("TextForOptions_Label")
        self.ValueForWin_Label = QtWidgets.QLabel(OptionsForm)
        self.ValueForWin_Label.setGeometry(QtCore.QRect(10, 50, 121, 20))
        self.ValueForWin_Label.setObjectName("ValueForWin_Label")
        self.MinValueForNewPlate_Label = QtWidgets.QLabel(OptionsForm)
        self.MinValueForNewPlate_Label.setGeometry(QtCore.QRect(10, 90, 201, 16))
        self.MinValueForNewPlate_Label.setObjectName("MinValueForNewPlate_Label")
        self.retranslateUi(OptionsForm)
        QtCore.QMetaObject.connectSlotsByName(OptionsForm)
        self.SaveOptions_PushButton.clicked.connect(self.save_options)
        self.load_options()

    def load_options(self):
        for i in range(1, 8):
            self.MinValueForNewPlate_ComboBox.addItem(str(2**i))
        for i in range(11, 15):
            self.ValueForWin_ComboBox.addItem(str(2**i))

    def save_options(self):
        self.parent.minValueForNewPlate[-1] = int(self.MinValueForNewPlate_ComboBox.currentText())
        self.parent.maxValueForWin[-1] = int(self.ValueForWin_ComboBox.currentText())
        self.close()

    def retranslateUi(self, OptionsForm):
        _translate = QtCore.QCoreApplication.translate
        OptionsForm.setWindowTitle(_translate("OptionsForm", "Настройки"))
        self.SaveOptions_PushButton.setText(_translate("OptionsForm", "Сохранить"))
        self.TextForOptions_Label.setText(_translate("OptionsForm", "Настройки 3-го уровня."))
        self.ValueForWin_Label.setText(_translate("OptionsForm", "Число для выигрыша:"))
        self.MinValueForNewPlate_Label.setText(_translate("OptionsForm", "Минимальное значение новой плитки:"))
