# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultOfGame.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtMultimedia
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QWidget

class Ui_ResultOfGameForm(QWidget):
    def __init__(self, parent):
        super(Ui_ResultOfGameForm, self).__init__(parent)
        self.parent = parent
        self.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.Window)
        self.setupUi(self)
        self.show()

    def setupUi(self, ResultOfGameForm):
        ResultOfGameForm.setObjectName("ResultOfGameForm")
        ResultOfGameForm.setFixedSize(500, 250)
        self.ResultOfGame_Label = QtWidgets.QLabel(ResultOfGameForm)
        self.ResultOfGame_Label.setGeometry(QtCore.QRect(0, 0, 221, 91))
        self.ResultOfGame_Label.setText("")
        self.ResultOfGame_Label.setObjectName("ResultOfGame_Label")
        self.retranslateUi(ResultOfGameForm)
        QtCore.QMetaObject.connectSlotsByName(ResultOfGameForm)
        self.produce_result()


    def produce_result(self):
        if self.parent.is_win():
            self.setWindowTitle('Вы выиграли! :)')
            size = QtGui.QImage('images/win.gif').size()
            self.setFixedSize(size)
            self.movie = QtGui.QMovie('images/win.gif')
            self.ResultOfGame_Label.setMovie(self.movie)
            self.ResultOfGame_Label.resize(size)
            self.movie.start()
            self.load_mp3('sounds/win.mp3')
            self.player.play()
        else:
            self.setWindowTitle('Вы проиграли :(')
            size = QtGui.QImage('images/gameover.gif').size()
            self.setFixedSize(size)
            self.movie = QtGui.QMovie('images/gameover.gif')
            self.ResultOfGame_Label.setMovie(self.movie)
            self.ResultOfGame_Label.resize(size)
            self.movie.start()
            self.load_mp3('sounds/gameover.mp3')
            self.player.play()

    def load_mp3(self, filename):
        media = QtCore.QUrl.fromLocalFile(filename)
        content = QtMultimedia.QMediaContent(media)
        self.player = QtMultimedia.QMediaPlayer()
        self.player.setMedia(content)



    def retranslateUi(self, ResultOfGameForm):
        _translate = QtCore.QCoreApplication.translate
        ResultOfGameForm.setWindowTitle(_translate("ResultOfGameForm", "Вы "))