# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectPlayerForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QWidget
from AddANewPlayerForm import Ui_AddANewPlayerForm
import sqlite3


class Ui_SelectPlayerForm(QWidget):
    def __init__(self, parent):
        super(Ui_SelectPlayerForm, self).__init__(parent)
        self.parent = parent
        self.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.Window)
        self.setupUi(self)
        self.show()

    def setupUi(self, SelectPlayerForm):
        SelectPlayerForm.setObjectName("SelectPlayerForm")
        SelectPlayerForm.setFixedSize(490, 500)
        self.SelectPlayerFromDataBase_PushButton = QtWidgets.QPushButton(SelectPlayerForm)
        self.SelectPlayerFromDataBase_PushButton.setGeometry(QtCore.QRect(330, 420, 150, 25))
        self.SelectPlayerFromDataBase_PushButton.setObjectName("SelectPlayerFromDataBase_PushButton")
        self.PlayersDataBase_TableWidget = QtWidgets.QTableWidget(SelectPlayerForm)
        self.PlayersDataBase_TableWidget.setGeometry(QtCore.QRect(10, 10, 470, 400))
        self.PlayersDataBase_TableWidget.setObjectName("PlayersDataBase_TableWidget")
        self.PlayersDataBase_TableWidget.setColumnCount(0)
        self.PlayersDataBase_TableWidget.setRowCount(0)
        self.AddANewPlayerToDataBase_PushButton = QtWidgets.QPushButton(SelectPlayerForm)
        self.AddANewPlayerToDataBase_PushButton.setGeometry(QtCore.QRect(10, 420, 150, 25))
        self.AddANewPlayerToDataBase_PushButton.setObjectName("AddANewPlayerToDataBase_PushButton")
        self.Debug_Label = QtWidgets.QLabel(SelectPlayerForm)
        self.Debug_Label.setGeometry(QtCore.QRect(10, 470, 350, 16))
        self.Debug_Label.setText("")
        self.Debug_Label.setObjectName("Debug_Label")
        self.DeletePlayerFromDataBase_PushButton = QtWidgets.QPushButton(SelectPlayerForm)
        self.DeletePlayerFromDataBase_PushButton.setGeometry(QtCore.QRect(170, 420, 150, 25))
        self.DeletePlayerFromDataBase_PushButton.setObjectName("DeletePlayerFromDataBase_PushButton")
        self.retranslateUi(SelectPlayerForm)
        QtCore.QMetaObject.connectSlotsByName(SelectPlayerForm)
        self.con = sqlite3.connect(self.parent.DataBaseName)
        self.cur = self.con.cursor()
        self.update_table()
        self.AddANewPlayerToDataBase_PushButton.clicked.connect(self.add_new_player)
        self.SelectPlayerFromDataBase_PushButton.clicked.connect(self.selectPlayer)
        self.DeletePlayerFromDataBase_PushButton.clicked.connect(self.delete_player)

    def add_new_player(self):
        self.parent.addANewPlayer = Ui_AddANewPlayerForm(self.parent)

    def update_table(self):
        self.ListOfPlayers = self.cur.execute('select id,name from players').fetchall()
        self.ResultOfPlayers = self.cur.execute('select id,best_result from players').fetchall()
        self.PlayersDataBase_TableWidget.setRowCount(len(self.ListOfPlayers))
        self.PlayersDataBase_TableWidget.setColumnCount(len(self.ListOfPlayers[0]))
        self.PlayersDataBase_TableWidget.setHorizontalHeaderLabels(['id','Имя'])
        for i, elem in enumerate(self.ListOfPlayers):
            for j, val in enumerate(elem):
                self.PlayersDataBase_TableWidget.setItem(i, j, QtWidgets.QTableWidgetItem(str(val)))
                self.PlayersDataBase_TableWidget.item(i, j).setFlags(QtCore.Qt.ItemIsEnabled)
        self.PlayersDataBase_TableWidget.setColumnWidth(0, self.PlayersDataBase_TableWidget.width() * 0.05)
        self.PlayersDataBase_TableWidget.setColumnWidth(1, self.PlayersDataBase_TableWidget.width() * 0.90)

    def selectPlayer(self):
        self.parent.CurrentPlayer_LineEdit.setText(
            self.PlayersDataBase_TableWidget.item(self.PlayersDataBase_TableWidget.currentRow(), 1).text())
        self.parent.BestScore_LineEdit.setText(
            str(self.ResultOfPlayers[self.PlayersDataBase_TableWidget.currentRow()][1]))
        self.con.close()
        self.parent.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.parent.currentPlayer = self.ResultOfPlayers[self.PlayersDataBase_TableWidget.currentRow()][0]
        self.parent.field = [[0,0,0,0] for i in range(4)]
        self.parent.count_score()
        self.parent.show_field()
        self.parent.field = []
        self.close()

    def delete_player(self):
        self.cur.execute('delete from players where id = ?'
                         ,(int(self.PlayersDataBase_TableWidget.item(
                self.PlayersDataBase_TableWidget.currentRow(), 0).text()),))
        self.con.commit()
        self.con.close()
        self.con = sqlite3.connect(self.parent.DataBaseName)
        self.cur = self.con.cursor()
        self.update_table()

    def retranslateUi(self, SelectPlayerForm):
        _translate = QtCore.QCoreApplication.translate
        SelectPlayerForm.setWindowTitle(_translate("SelectPlayerForm", "Выберите пользователя"))
        self.SelectPlayerFromDataBase_PushButton.setText(_translate("SelectPlayerForm", "Выбрать пользователя"))
        self.AddANewPlayerToDataBase_PushButton.setText(_translate("SelectPlayerForm", "Добавить пользователя"))
        self.DeletePlayerFromDataBase_PushButton.setText(_translate("SelectPlayerForm", "Удалить пользователя"))